#!/bin/bash

set -e

if [ -z ${PYTHON_PATH} ]; then
    PYTHON_PATH=python3
fi

script_path=$(cd `dirname $0` && pwd)
cd "${script_path}"
rm -rf dist
${PYTHON_PATH} setup.py bdist_wheel
cd dist
pip3 install --user siqadtools*.whl
