#!/bin/bash

# TODO START ###################################################################################
# After figuring out CMAKE for all Linux packages, use this script to call CMAKE.
# Windows is a special case where no matter what I do with CMAKE, there's no way to make a cross-compiled SiQAD that works. Use qmake for Windows SiQAD, and CMAKE for everything else.
# TODO END #####################################################################################

set -e

# determine number of physical cores to use for compilation
cpu_cores=$(grep "^core id" /proc/cpuinfo | sort -u | wc -l)
multicore_compile="-j $cpu_cores"

# store handy directories
make_dir=$(pwd)
qmake_dir=$(cd `dirname $0` && pwd)

# path to Breeze Qt icon theme for cross-compilation
# an example is to clone https://github.com/KDE/breeze-icons and point the following variable to the icons directory.
qt_theme_path=$HOME/global/siqad-cross-compilation-resources/breeze-icons/icons

# figure out which qmake command to use
if [ "$FOR_OS" == "win32" ]; then
    export FOR_OS
    export PATH="$PATH:/usr/lib/mxe/usr/bin"
    QMAKE_COMMAND=i686-w64-mingw32.static-qmake-qt5
    make_flag=release
elif [ "$FOR_OS" == "win64" ]; then
    export FOR_OS
    export PATH="$PATH:/usr/lib/mxe/usr/bin"
    QMAKE_COMMAND=x86_64-w64-mingw32.static-qmake-qt5
    make_flag=release
else
    QMAKE_COMMAND=qmake
fi

# make SWIG at the central location and copy to desired destinations
if [ "$@" == "--swig" ] && [ "$FOR_OS" != "win32"]
then
    echo "Building SWIG SiQADConnector at central location... $FOR_OS"
    cd $qmake_dir/src/phys/siqadconn
    ./swig_generate_and_compile FOR_OS=$FOR_OS

    # cp lib/* $qmake_dir/src/phys/exhaustive_gs/src
    cp lib/* $qmake_dir/src/phys/qpuanneal/src
    cp lib/* $qmake_dir/src/phys/afmmarcus/src
    cp lib/* $qmake_dir/src/phys/poissolver/FEM/src/python
    cp lib/* $qmake_dir/src/plugins/db_pattern_recognition
    cp lib/* $qmake_dir/src/phys/exhaustive_gs/src
fi

# make simanneal
echo "Building SimAnneal... $FOR_OS"
cd $qmake_dir/src/phys/simanneal
make $multicore_compile FOR_OS=$FOR_OS

# Uncomment particular sections if you want to build a specific version of SWIG for that engine

## make qpuanneal
#echo "Building QPUAnneal... $FOR_OS"
#if [[ "$@" == "-swig" ]]
#then
#    echo "Building swig for QPUAnneal"
#    cd $qmake_dir/src/phys/qpuanneal/src/swig_siqadconn
#    ./swig_generate_and_compile FOR_OS=$FOR_OS
#fi
#
## make afmmarcus
#echo "Building AFMMarcus... $FOR_OS"
#if [[ "$@" == "-swig" ]]
#then
#    echo "Building swig for AFMMarcus"
#    cd $qmake_dir/src/phys/afmmarcus/src/swig_siqadconn
#    ./swig_generate_and_compile FOR_OS=$FOR_OS
#fi
#
# # make poissolver
# echo "Building PoisSolver... $FOR_OS"
# if [[ "$@" == "-swig" ]]
# then
#    echo "Building swig for PoisSolver"
#    cd $qmake_dir/src/phys/poissolver/FEM/src/python/swig_siqadconn
#    ./swig_generate_and_compile FOR_OS=$FOR_OS
# fi

# use qmake to create Make files for the GUI
cd "$make_dir"
echo "Running qmake..."
$QMAKE_COMMAND "$qmake_dir"

# make the GUI and copy physics engine files over
echo "Building GUI..."
cd $make_dir && make $make_flag $multicore_compile
make install


# extra actions if building for Windows
if [ "$FOR_OS" == "win64" ] || [ "$FOR_OS" == "win32" ] ; then
    cd "$make_dir/build/release/"

    # Clean up
    rm -rf .moc .obj .qrc

    # Copy Qt theme icons since Windows doesn't have one
    target_qt_theme_path=icons/breeze
    mkdir -p "$target_qt_theme_path"
    cp -r "$qt_theme_path/"* "$target_qt_theme_path"

    # PoisSolver and QPUAnneal not officially supported on Windows yet
    cd "$make_dir/build/release/src/phys/"
    rm -rf poissolver
    rm -rf qpuanneal

    # Change physeng file to include .exe suffix for engines that have compiled binaries
    sed -i 's/<\/bin_path>/\.exe&/' ./simanneal/sim_anneal.physeng

    # Create an archive
    cd "$make_dir/build/"
    archive_name=siqad_64.zip
    rm -f "$archive_name"
    zip -r "$archive_name" "release"
fi
