# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_siqadconn')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_siqadconn')
    _siqadconn = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_siqadconn', [dirname(__file__)])
        except ImportError:
            import _siqadconn
            return _siqadconn
        try:
            _mod = imp.load_module('_siqadconn', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _siqadconn = swig_import_helper()
    del swig_import_helper
else:
    import _siqadconn
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _siqadconn.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _siqadconn.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _siqadconn.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _siqadconn.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _siqadconn.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _siqadconn.SwigPyIterator_equal(self, x)

    def copy(self):
        return _siqadconn.SwigPyIterator_copy(self)

    def next(self):
        return _siqadconn.SwigPyIterator_next(self)

    def __next__(self):
        return _siqadconn.SwigPyIterator___next__(self)

    def previous(self):
        return _siqadconn.SwigPyIterator_previous(self)

    def advance(self, n):
        return _siqadconn.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _siqadconn.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _siqadconn.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _siqadconn.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _siqadconn.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _siqadconn.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _siqadconn.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _siqadconn.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _siqadconn.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _siqadconn.IntVector___nonzero__(self)

    def __bool__(self):
        return _siqadconn.IntVector___bool__(self)

    def __len__(self):
        return _siqadconn.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _siqadconn.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _siqadconn.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _siqadconn.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _siqadconn.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _siqadconn.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _siqadconn.IntVector___setitem__(self, *args)

    def pop(self):
        return _siqadconn.IntVector_pop(self)

    def append(self, x):
        return _siqadconn.IntVector_append(self, x)

    def empty(self):
        return _siqadconn.IntVector_empty(self)

    def size(self):
        return _siqadconn.IntVector_size(self)

    def swap(self, v):
        return _siqadconn.IntVector_swap(self, v)

    def begin(self):
        return _siqadconn.IntVector_begin(self)

    def end(self):
        return _siqadconn.IntVector_end(self)

    def rbegin(self):
        return _siqadconn.IntVector_rbegin(self)

    def rend(self):
        return _siqadconn.IntVector_rend(self)

    def clear(self):
        return _siqadconn.IntVector_clear(self)

    def get_allocator(self):
        return _siqadconn.IntVector_get_allocator(self)

    def pop_back(self):
        return _siqadconn.IntVector_pop_back(self)

    def erase(self, *args):
        return _siqadconn.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _siqadconn.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _siqadconn.IntVector_push_back(self, x)

    def front(self):
        return _siqadconn.IntVector_front(self)

    def back(self):
        return _siqadconn.IntVector_back(self)

    def assign(self, n, x):
        return _siqadconn.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _siqadconn.IntVector_resize(self, *args)

    def insert(self, *args):
        return _siqadconn.IntVector_insert(self, *args)

    def reserve(self, n):
        return _siqadconn.IntVector_reserve(self, n)

    def capacity(self):
        return _siqadconn.IntVector_capacity(self)
    __swig_destroy__ = _siqadconn.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _siqadconn.IntVector_swigregister
IntVector_swigregister(IntVector)

class StringPair(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringPair, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringPair, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _siqadconn.new_StringPair(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["first"] = _siqadconn.StringPair_first_set
    __swig_getmethods__["first"] = _siqadconn.StringPair_first_get
    if _newclass:
        first = _swig_property(_siqadconn.StringPair_first_get, _siqadconn.StringPair_first_set)
    __swig_setmethods__["second"] = _siqadconn.StringPair_second_set
    __swig_getmethods__["second"] = _siqadconn.StringPair_second_get
    if _newclass:
        second = _swig_property(_siqadconn.StringPair_second_get, _siqadconn.StringPair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _siqadconn.delete_StringPair
    __del__ = lambda self: None
StringPair_swigregister = _siqadconn.StringPair_swigregister
StringPair_swigregister(StringPair)

class StringPairVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringPairVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringPairVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _siqadconn.StringPairVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _siqadconn.StringPairVector___nonzero__(self)

    def __bool__(self):
        return _siqadconn.StringPairVector___bool__(self)

    def __len__(self):
        return _siqadconn.StringPairVector___len__(self)

    def __getslice__(self, i, j):
        return _siqadconn.StringPairVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _siqadconn.StringPairVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _siqadconn.StringPairVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _siqadconn.StringPairVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _siqadconn.StringPairVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _siqadconn.StringPairVector___setitem__(self, *args)

    def pop(self):
        return _siqadconn.StringPairVector_pop(self)

    def append(self, x):
        return _siqadconn.StringPairVector_append(self, x)

    def empty(self):
        return _siqadconn.StringPairVector_empty(self)

    def size(self):
        return _siqadconn.StringPairVector_size(self)

    def swap(self, v):
        return _siqadconn.StringPairVector_swap(self, v)

    def begin(self):
        return _siqadconn.StringPairVector_begin(self)

    def end(self):
        return _siqadconn.StringPairVector_end(self)

    def rbegin(self):
        return _siqadconn.StringPairVector_rbegin(self)

    def rend(self):
        return _siqadconn.StringPairVector_rend(self)

    def clear(self):
        return _siqadconn.StringPairVector_clear(self)

    def get_allocator(self):
        return _siqadconn.StringPairVector_get_allocator(self)

    def pop_back(self):
        return _siqadconn.StringPairVector_pop_back(self)

    def erase(self, *args):
        return _siqadconn.StringPairVector_erase(self, *args)

    def __init__(self, *args):
        this = _siqadconn.new_StringPairVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _siqadconn.StringPairVector_push_back(self, x)

    def front(self):
        return _siqadconn.StringPairVector_front(self)

    def back(self):
        return _siqadconn.StringPairVector_back(self)

    def assign(self, n, x):
        return _siqadconn.StringPairVector_assign(self, n, x)

    def resize(self, *args):
        return _siqadconn.StringPairVector_resize(self, *args)

    def insert(self, *args):
        return _siqadconn.StringPairVector_insert(self, *args)

    def reserve(self, n):
        return _siqadconn.StringPairVector_reserve(self, n)

    def capacity(self):
        return _siqadconn.StringPairVector_capacity(self)
    __swig_destroy__ = _siqadconn.delete_StringPairVector
    __del__ = lambda self: None
StringPairVector_swigregister = _siqadconn.StringPairVector_swigregister
StringPairVector_swigregister(StringPairVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _siqadconn.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _siqadconn.StringVector___nonzero__(self)

    def __bool__(self):
        return _siqadconn.StringVector___bool__(self)

    def __len__(self):
        return _siqadconn.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _siqadconn.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _siqadconn.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _siqadconn.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _siqadconn.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _siqadconn.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _siqadconn.StringVector___setitem__(self, *args)

    def pop(self):
        return _siqadconn.StringVector_pop(self)

    def append(self, x):
        return _siqadconn.StringVector_append(self, x)

    def empty(self):
        return _siqadconn.StringVector_empty(self)

    def size(self):
        return _siqadconn.StringVector_size(self)

    def swap(self, v):
        return _siqadconn.StringVector_swap(self, v)

    def begin(self):
        return _siqadconn.StringVector_begin(self)

    def end(self):
        return _siqadconn.StringVector_end(self)

    def rbegin(self):
        return _siqadconn.StringVector_rbegin(self)

    def rend(self):
        return _siqadconn.StringVector_rend(self)

    def clear(self):
        return _siqadconn.StringVector_clear(self)

    def get_allocator(self):
        return _siqadconn.StringVector_get_allocator(self)

    def pop_back(self):
        return _siqadconn.StringVector_pop_back(self)

    def erase(self, *args):
        return _siqadconn.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _siqadconn.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _siqadconn.StringVector_push_back(self, x)

    def front(self):
        return _siqadconn.StringVector_front(self)

    def back(self):
        return _siqadconn.StringVector_back(self)

    def assign(self, n, x):
        return _siqadconn.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _siqadconn.StringVector_resize(self, *args)

    def insert(self, *args):
        return _siqadconn.StringVector_insert(self, *args)

    def reserve(self, n):
        return _siqadconn.StringVector_reserve(self, n)

    def capacity(self):
        return _siqadconn.StringVector_capacity(self)
    __swig_destroy__ = _siqadconn.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _siqadconn.StringVector_swigregister
StringVector_swigregister(StringVector)

class StringVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector2D, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _siqadconn.StringVector2D_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _siqadconn.StringVector2D___nonzero__(self)

    def __bool__(self):
        return _siqadconn.StringVector2D___bool__(self)

    def __len__(self):
        return _siqadconn.StringVector2D___len__(self)

    def __getslice__(self, i, j):
        return _siqadconn.StringVector2D___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _siqadconn.StringVector2D___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _siqadconn.StringVector2D___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _siqadconn.StringVector2D___delitem__(self, *args)

    def __getitem__(self, *args):
        return _siqadconn.StringVector2D___getitem__(self, *args)

    def __setitem__(self, *args):
        return _siqadconn.StringVector2D___setitem__(self, *args)

    def pop(self):
        return _siqadconn.StringVector2D_pop(self)

    def append(self, x):
        return _siqadconn.StringVector2D_append(self, x)

    def empty(self):
        return _siqadconn.StringVector2D_empty(self)

    def size(self):
        return _siqadconn.StringVector2D_size(self)

    def swap(self, v):
        return _siqadconn.StringVector2D_swap(self, v)

    def begin(self):
        return _siqadconn.StringVector2D_begin(self)

    def end(self):
        return _siqadconn.StringVector2D_end(self)

    def rbegin(self):
        return _siqadconn.StringVector2D_rbegin(self)

    def rend(self):
        return _siqadconn.StringVector2D_rend(self)

    def clear(self):
        return _siqadconn.StringVector2D_clear(self)

    def get_allocator(self):
        return _siqadconn.StringVector2D_get_allocator(self)

    def pop_back(self):
        return _siqadconn.StringVector2D_pop_back(self)

    def erase(self, *args):
        return _siqadconn.StringVector2D_erase(self, *args)

    def __init__(self, *args):
        this = _siqadconn.new_StringVector2D(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _siqadconn.StringVector2D_push_back(self, x)

    def front(self):
        return _siqadconn.StringVector2D_front(self)

    def back(self):
        return _siqadconn.StringVector2D_back(self)

    def assign(self, n, x):
        return _siqadconn.StringVector2D_assign(self, n, x)

    def resize(self, *args):
        return _siqadconn.StringVector2D_resize(self, *args)

    def insert(self, *args):
        return _siqadconn.StringVector2D_insert(self, *args)

    def reserve(self, n):
        return _siqadconn.StringVector2D_reserve(self, n)

    def capacity(self):
        return _siqadconn.StringVector2D_capacity(self)
    __swig_destroy__ = _siqadconn.delete_StringVector2D
    __del__ = lambda self: None
StringVector2D_swigregister = _siqadconn.StringVector2D_swigregister
StringVector2D_swigregister(StringVector2D)

class StringMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringMap, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _siqadconn.StringMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _siqadconn.StringMap___nonzero__(self)

    def __bool__(self):
        return _siqadconn.StringMap___bool__(self)

    def __len__(self):
        return _siqadconn.StringMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _siqadconn.StringMap___getitem__(self, key)

    def __delitem__(self, key):
        return _siqadconn.StringMap___delitem__(self, key)

    def has_key(self, key):
        return _siqadconn.StringMap_has_key(self, key)

    def keys(self):
        return _siqadconn.StringMap_keys(self)

    def values(self):
        return _siqadconn.StringMap_values(self)

    def items(self):
        return _siqadconn.StringMap_items(self)

    def __contains__(self, key):
        return _siqadconn.StringMap___contains__(self, key)

    def key_iterator(self):
        return _siqadconn.StringMap_key_iterator(self)

    def value_iterator(self):
        return _siqadconn.StringMap_value_iterator(self)

    def __setitem__(self, *args):
        return _siqadconn.StringMap___setitem__(self, *args)

    def asdict(self):
        return _siqadconn.StringMap_asdict(self)

    def __init__(self, *args):
        this = _siqadconn.new_StringMap(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _siqadconn.StringMap_empty(self)

    def size(self):
        return _siqadconn.StringMap_size(self)

    def swap(self, v):
        return _siqadconn.StringMap_swap(self, v)

    def begin(self):
        return _siqadconn.StringMap_begin(self)

    def end(self):
        return _siqadconn.StringMap_end(self)

    def rbegin(self):
        return _siqadconn.StringMap_rbegin(self)

    def rend(self):
        return _siqadconn.StringMap_rend(self)

    def clear(self):
        return _siqadconn.StringMap_clear(self)

    def get_allocator(self):
        return _siqadconn.StringMap_get_allocator(self)

    def count(self, x):
        return _siqadconn.StringMap_count(self, x)

    def erase(self, *args):
        return _siqadconn.StringMap_erase(self, *args)

    def find(self, x):
        return _siqadconn.StringMap_find(self, x)

    def lower_bound(self, x):
        return _siqadconn.StringMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _siqadconn.StringMap_upper_bound(self, x)
    __swig_destroy__ = _siqadconn.delete_StringMap
    __del__ = lambda self: None
StringMap_swigregister = _siqadconn.StringMap_swigregister
StringMap_swigregister(StringMap)

class SiQADConnector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SiQADConnector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SiQADConnector, name)
    __repr__ = _swig_repr

    def __init__(self, eng_name, input_path, output_path):
        this = _siqadconn.new_SiQADConnector(eng_name, input_path, output_path)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _siqadconn.delete_SiQADConnector
    __del__ = lambda self: None

    def writeResultsXml(self):
        return _siqadconn.SiQADConnector_writeResultsXml(self)

    def setExport(self, *args):
        return _siqadconn.SiQADConnector_setExport(self, *args)

    def parameterExists(self, key):
        return _siqadconn.SiQADConnector_parameterExists(self, key)

    def getParameter(self, key):
        return _siqadconn.SiQADConnector_getParameter(self, key)

    def dbCollection(self):
        return _siqadconn.SiQADConnector_dbCollection(self)

    def electrodeCollection(self):
        return _siqadconn.SiQADConnector_electrodeCollection(self)

    def inputPath(self):
        return _siqadconn.SiQADConnector_inputPath(self)

    def setOutputPath(self, path):
        return _siqadconn.SiQADConnector_setOutputPath(self, path)

    def outputPath(self):
        return _siqadconn.SiQADConnector_outputPath(self)

    def setExport(self, *args, **kwargs):
      for key in kwargs:
        if key == "db_loc":
          self.setDBLocData(StringPairVector(self.tuplify(kwargs[key])))
        elif key == "db_charge":
          self.setDBChargeData(StringPairVector(self.tuplify(kwargs[key])))
        elif key == "potential":
          self.setElecPotentialData(StringVector2D(self.tuplify(kwargs[key])))
        elif key == "db_pot":
          self.setDBPotData(StringVector2D(self.tuplify(kwargs[key])))


    def exportElecPotentialData(self, data_in):
      self.setElecPotentialData(StringVector2D(self.tuplify(data_in)))


    def exportDBPotData(self, data_in):
      self.setDBPotData(StringVector2D(self.tuplify(data_in)))


    def exportDBChargeData(self, data_in):
      self.setDBChargeData(StringPairVector(self.tuplify(data_in)))


    def exportDBLocData(self, data_in):
      self.setDBLocData(StringPairVector(self.tuplify(data_in)))


    def tuplify(self, data):
      if hasattr(data,'__iter__') and not hasattr(data, "strip"):
        return tuple(self.tuplify(i) for i in data)
      else:
        return str(data)

SiQADConnector_swigregister = _siqadconn.SiQADConnector_swigregister
SiQADConnector_swigregister(SiQADConnector)

class Layer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Layer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Layer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _siqadconn.new_Layer(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["name"] = _siqadconn.Layer_name_set
    __swig_getmethods__["name"] = _siqadconn.Layer_name_get
    if _newclass:
        name = _swig_property(_siqadconn.Layer_name_get, _siqadconn.Layer_name_set)
    __swig_setmethods__["type"] = _siqadconn.Layer_type_set
    __swig_getmethods__["type"] = _siqadconn.Layer_type_get
    if _newclass:
        type = _swig_property(_siqadconn.Layer_type_get, _siqadconn.Layer_type_set)
    __swig_setmethods__["zoffset"] = _siqadconn.Layer_zoffset_set
    __swig_getmethods__["zoffset"] = _siqadconn.Layer_zoffset_get
    if _newclass:
        zoffset = _swig_property(_siqadconn.Layer_zoffset_get, _siqadconn.Layer_zoffset_set)
    __swig_setmethods__["zheight"] = _siqadconn.Layer_zheight_set
    __swig_getmethods__["zheight"] = _siqadconn.Layer_zheight_get
    if _newclass:
        zheight = _swig_property(_siqadconn.Layer_zheight_get, _siqadconn.Layer_zheight_set)
    __swig_destroy__ = _siqadconn.delete_Layer
    __del__ = lambda self: None
Layer_swigregister = _siqadconn.Layer_swigregister
Layer_swigregister(Layer)

class DBDot(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DBDot, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DBDot, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _siqadconn.DBDot_x_set
    __swig_getmethods__["x"] = _siqadconn.DBDot_x_get
    if _newclass:
        x = _swig_property(_siqadconn.DBDot_x_get, _siqadconn.DBDot_x_set)
    __swig_setmethods__["y"] = _siqadconn.DBDot_y_set
    __swig_getmethods__["y"] = _siqadconn.DBDot_y_get
    if _newclass:
        y = _swig_property(_siqadconn.DBDot_y_get, _siqadconn.DBDot_y_set)
    __swig_setmethods__["n"] = _siqadconn.DBDot_n_set
    __swig_getmethods__["n"] = _siqadconn.DBDot_n_get
    if _newclass:
        n = _swig_property(_siqadconn.DBDot_n_get, _siqadconn.DBDot_n_set)
    __swig_setmethods__["m"] = _siqadconn.DBDot_m_set
    __swig_getmethods__["m"] = _siqadconn.DBDot_m_get
    if _newclass:
        m = _swig_property(_siqadconn.DBDot_m_get, _siqadconn.DBDot_m_set)
    __swig_setmethods__["l"] = _siqadconn.DBDot_l_set
    __swig_getmethods__["l"] = _siqadconn.DBDot_l_get
    if _newclass:
        l = _swig_property(_siqadconn.DBDot_l_get, _siqadconn.DBDot_l_set)

    def __init__(self, in_x, in_y, n, m, l):
        this = _siqadconn.new_DBDot(in_x, in_y, n, m, l)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _siqadconn.delete_DBDot
    __del__ = lambda self: None
DBDot_swigregister = _siqadconn.DBDot_swigregister
DBDot_swigregister(DBDot)

class DBIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DBIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DBIterator, name)
    __repr__ = _swig_repr

    def __init__(self, root, begin=True):
        this = _siqadconn.new_DBIterator(root, begin)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __eq__(self, other):
        return _siqadconn.DBIterator___eq__(self, other)

    def __ne__(self, other):
        return _siqadconn.DBIterator___ne__(self, other)

    def __ref__(self):
        return _siqadconn.DBIterator___ref__(self)

    def setCollection(self, coll):
        return _siqadconn.DBIterator_setCollection(self, coll)
    __swig_setmethods__["collection"] = _siqadconn.DBIterator_collection_set
    __swig_getmethods__["collection"] = _siqadconn.DBIterator_collection_get
    if _newclass:
        collection = _swig_property(_siqadconn.DBIterator_collection_get, _siqadconn.DBIterator_collection_set)

    def __iter__(self):
        return _siqadconn.DBIterator___iter__(self)

    def __next__(self):
      db = _siqadconn.DBIterator___next__(self)
      if db == None:
        raise StopIteration
      else:
        return db


    __swig_destroy__ = _siqadconn.delete_DBIterator
    __del__ = lambda self: None
DBIterator_swigregister = _siqadconn.DBIterator_swigregister
DBIterator_swigregister(DBIterator)

class DBCollection(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DBCollection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DBCollection, name)
    __repr__ = _swig_repr

    def __init__(self, db_tree_in):
        this = _siqadconn.new_DBCollection(db_tree_in)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def begin(self):
        return _siqadconn.DBCollection_begin(self)

    def end(self):
        return _siqadconn.DBCollection_end(self)
    __swig_setmethods__["db_tree_inner"] = _siqadconn.DBCollection_db_tree_inner_set
    __swig_getmethods__["db_tree_inner"] = _siqadconn.DBCollection_db_tree_inner_get
    if _newclass:
        db_tree_inner = _swig_property(_siqadconn.DBCollection_db_tree_inner_get, _siqadconn.DBCollection_db_tree_inner_set)

    def __iter__(self):
        return _siqadconn.DBCollection___iter__(self)
    __swig_destroy__ = _siqadconn.delete_DBCollection
    __del__ = lambda self: None
DBCollection_swigregister = _siqadconn.DBCollection_swigregister
DBCollection_swigregister(DBCollection)

class Electrode(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Electrode, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Electrode, name)
    __repr__ = _swig_repr
    __swig_setmethods__["layer_id"] = _siqadconn.Electrode_layer_id_set
    __swig_getmethods__["layer_id"] = _siqadconn.Electrode_layer_id_get
    if _newclass:
        layer_id = _swig_property(_siqadconn.Electrode_layer_id_get, _siqadconn.Electrode_layer_id_set)
    __swig_setmethods__["x1"] = _siqadconn.Electrode_x1_set
    __swig_getmethods__["x1"] = _siqadconn.Electrode_x1_get
    if _newclass:
        x1 = _swig_property(_siqadconn.Electrode_x1_get, _siqadconn.Electrode_x1_set)
    __swig_setmethods__["x2"] = _siqadconn.Electrode_x2_set
    __swig_getmethods__["x2"] = _siqadconn.Electrode_x2_get
    if _newclass:
        x2 = _swig_property(_siqadconn.Electrode_x2_get, _siqadconn.Electrode_x2_set)
    __swig_setmethods__["y1"] = _siqadconn.Electrode_y1_set
    __swig_getmethods__["y1"] = _siqadconn.Electrode_y1_get
    if _newclass:
        y1 = _swig_property(_siqadconn.Electrode_y1_get, _siqadconn.Electrode_y1_set)
    __swig_setmethods__["y2"] = _siqadconn.Electrode_y2_set
    __swig_getmethods__["y2"] = _siqadconn.Electrode_y2_get
    if _newclass:
        y2 = _swig_property(_siqadconn.Electrode_y2_get, _siqadconn.Electrode_y2_set)
    __swig_setmethods__["potential"] = _siqadconn.Electrode_potential_set
    __swig_getmethods__["potential"] = _siqadconn.Electrode_potential_get
    if _newclass:
        potential = _swig_property(_siqadconn.Electrode_potential_get, _siqadconn.Electrode_potential_set)
    __swig_setmethods__["phase"] = _siqadconn.Electrode_phase_set
    __swig_getmethods__["phase"] = _siqadconn.Electrode_phase_get
    if _newclass:
        phase = _swig_property(_siqadconn.Electrode_phase_get, _siqadconn.Electrode_phase_set)
    __swig_setmethods__["electrode_type"] = _siqadconn.Electrode_electrode_type_set
    __swig_getmethods__["electrode_type"] = _siqadconn.Electrode_electrode_type_get
    if _newclass:
        electrode_type = _swig_property(_siqadconn.Electrode_electrode_type_get, _siqadconn.Electrode_electrode_type_set)
    __swig_setmethods__["pixel_per_angstrom"] = _siqadconn.Electrode_pixel_per_angstrom_set
    __swig_getmethods__["pixel_per_angstrom"] = _siqadconn.Electrode_pixel_per_angstrom_get
    if _newclass:
        pixel_per_angstrom = _swig_property(_siqadconn.Electrode_pixel_per_angstrom_get, _siqadconn.Electrode_pixel_per_angstrom_set)

    def __init__(self, in_layer_id, in_x1, in_x2, in_y1, in_y2, in_potential, in_phase, in_electrode_type, in_pixel_per_angstrom):
        this = _siqadconn.new_Electrode(in_layer_id, in_x1, in_x2, in_y1, in_y2, in_potential, in_phase, in_electrode_type, in_pixel_per_angstrom)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _siqadconn.delete_Electrode
    __del__ = lambda self: None
Electrode_swigregister = _siqadconn.Electrode_swigregister
Electrode_swigregister(Electrode)

class ElecIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ElecIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ElecIterator, name)
    __repr__ = _swig_repr

    def __init__(self, root, begin=True):
        this = _siqadconn.new_ElecIterator(root, begin)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __eq__(self, other):
        return _siqadconn.ElecIterator___eq__(self, other)

    def __ne__(self, other):
        return _siqadconn.ElecIterator___ne__(self, other)

    def __ref__(self):
        return _siqadconn.ElecIterator___ref__(self)

    def setCollection(self, coll):
        return _siqadconn.ElecIterator_setCollection(self, coll)
    __swig_setmethods__["collection"] = _siqadconn.ElecIterator_collection_set
    __swig_getmethods__["collection"] = _siqadconn.ElecIterator_collection_get
    if _newclass:
        collection = _swig_property(_siqadconn.ElecIterator_collection_get, _siqadconn.ElecIterator_collection_set)

    def __iter__(self):
        return _siqadconn.ElecIterator___iter__(self)

    def __next__(self):
      elec = _siqadconn.ElecIterator___next__(self)
      if elec == None:
        raise StopIteration
      else:
        return elec


    __swig_destroy__ = _siqadconn.delete_ElecIterator
    __del__ = lambda self: None
ElecIterator_swigregister = _siqadconn.ElecIterator_swigregister
ElecIterator_swigregister(ElecIterator)

class ElectrodeCollection(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ElectrodeCollection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ElectrodeCollection, name)
    __repr__ = _swig_repr

    def __init__(self, elec_tree_in):
        this = _siqadconn.new_ElectrodeCollection(elec_tree_in)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def begin(self):
        return _siqadconn.ElectrodeCollection_begin(self)

    def end(self):
        return _siqadconn.ElectrodeCollection_end(self)
    __swig_setmethods__["elec_tree_inner"] = _siqadconn.ElectrodeCollection_elec_tree_inner_set
    __swig_getmethods__["elec_tree_inner"] = _siqadconn.ElectrodeCollection_elec_tree_inner_get
    if _newclass:
        elec_tree_inner = _swig_property(_siqadconn.ElectrodeCollection_elec_tree_inner_get, _siqadconn.ElectrodeCollection_elec_tree_inner_set)

    def __iter__(self):
        return _siqadconn.ElectrodeCollection___iter__(self)
    __swig_destroy__ = _siqadconn.delete_ElectrodeCollection
    __del__ = lambda self: None
ElectrodeCollection_swigregister = _siqadconn.ElectrodeCollection_swigregister
ElectrodeCollection_swigregister(ElectrodeCollection)

class Aggregate(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Aggregate, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Aggregate, name)
    __repr__ = _swig_repr
    __swig_setmethods__["aggs"] = _siqadconn.Aggregate_aggs_set
    __swig_getmethods__["aggs"] = _siqadconn.Aggregate_aggs_get
    if _newclass:
        aggs = _swig_property(_siqadconn.Aggregate_aggs_get, _siqadconn.Aggregate_aggs_set)
    __swig_setmethods__["dbs"] = _siqadconn.Aggregate_dbs_set
    __swig_getmethods__["dbs"] = _siqadconn.Aggregate_dbs_get
    if _newclass:
        dbs = _swig_property(_siqadconn.Aggregate_dbs_get, _siqadconn.Aggregate_dbs_set)
    __swig_setmethods__["elecs"] = _siqadconn.Aggregate_elecs_set
    __swig_getmethods__["elecs"] = _siqadconn.Aggregate_elecs_get
    if _newclass:
        elecs = _swig_property(_siqadconn.Aggregate_elecs_get, _siqadconn.Aggregate_elecs_set)

    def size(self):
        return _siqadconn.Aggregate_size(self)

    def __init__(self):
        this = _siqadconn.new_Aggregate()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _siqadconn.delete_Aggregate
    __del__ = lambda self: None
Aggregate_swigregister = _siqadconn.Aggregate_swigregister
Aggregate_swigregister(Aggregate)

# This file is compatible with both classic and new-style classes.


